const NODE_URL = "http://localhost:8080";

const DEFAULT_FILTER_ROOM_NAME = "all";
const DEFAULT_SORT_ROOM_NAME = "regularPrice-ASC";

const DEFAULT_FILTER_BOOKING_NAME = "all";
const DEFAULT_SORT_BOOKING_NAME = "startDate-DESC";

const DEFAULT_CUR_PAGE = 1;
const DEFAULT_PAGE_SIZE = 3;

export {
  NODE_URL,
  DEFAULT_FILTER_ROOM_NAME,
  DEFAULT_SORT_ROOM_NAME,
  DEFAULT_FILTER_BOOKING_NAME,
  DEFAULT_SORT_BOOKING_NAME,
  DEFAULT_PAGE_SIZE,
  DEFAULT_CUR_PAGE,
};
